### ISSUE TITLE
No need to check Play Store for EN latest version

### ISSUE THREAD

**Issue by SunsetMkt** [respectZ/blue-archive-viewer#12]
https://github.com/respectZ/blue-archive-viewer/blob/main/py/api/en/main.py#L52

Regardless of which version number is sent to `version-check` (but it must be an existing version), the returned `latest_build_version` and `latest_build_number` are the latest versions, but `resource_path` is the version that was sent.

So just send two requests, the first to get latest version and update `body`, the second to get latest `resource_path`.

**Comment by SunsetMkt** [comment]
https://github.com/respectZ/blue-archive-viewer/blob/main/README.md?plain=1#L61

`dump.cs` is an output from [Il2CppDumper](https://github.com/Perfare/Il2CppDumper). There's no need to update it frequently.

To create a workflow for it, you need to build Il2CppDumper for Linux, since there's no official build. (`dotnet build` will be okay)

**Comment by SunsetMkt** [comment]
https://github.com/respectZ/blue-archive-viewer/blob/main/README.md?plain=1#L66

It's possible to automatically get JP URL. Extract `GameMainConfig` (`TextAsset`) from unzipped game OBB with `UnityPy` and decrypt it like a json. Check for the encrypted key `ServerInfoDataUrl` to get the resource link.

**Comment by respectZ** [comment]
Thanks for the info!
For the `dump.cs`, I just put them there to track it since I need it to generate the flatbuf and extracting the tables. IIRC 1.37 and 1.38 is different

Unfortunately, I have no luck on decrypting `GameMainConfig`

I suppose it's possible to create 100% automatic workflow to update everything

**Comment by SunsetMkt** [comment]
```python
import base64
import json

import libs.TableEncryptionService as TableEncryptionService


def NewEncryptString(value: str, key: bytes) -> str:
    if not value or len(value) < 8:
        return value.encode() if value else b""
    raw = value.encode("utf-16-le")
    return base64.b64encode(TableEncryptionService._XOR(raw, key)).decode()


# GameMainConfig is extracted from game OBB by UnityPy
with open("GameMainConfig", "rb") as f:
    data = f.read()
    data = base64.b64encode(data)
    data = TableEncryptionService.ConvertString(
        data, TableEncryptionService.CreateKey("GameMainConfig")
    )
    data = json.loads(data)
    crypted_key = NewEncryptString(
        "ServerInfoDataUrl", TableEncryptionService.CreateKey("ServerInfoDataUrl")
    )
    crypted_value = data[crypted_key]
    value = TableEncryptionService.ConvertString(
        crypted_value, TableEncryptionService.CreateKey("ServerInfoDataUrl")
    )
    print(value)
```
